version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - export SKIP="false"
      - if [[ "$(git log -1 HEAD --pretty=format:%s)" == *\[test\]* ]]; then echo "Installing yarn..." && npm install -g yarn; else export SKIP="true"; fi
  pre_build:
    commands:
      - if [[ "$SKIP" == "true" ]]; then echo "Skipping source NPM dependencies install..."; else echo "Installing source NPM dependencies..." && yarn; fi
  build:
    commands:
      - if [[ "$SKIP" == "true" ]]; then echo "Skipping tests..." && exit 1; else echo "Testing UI..." && yarn test; fi
      - export S3_DIR_DATE=$(date +'%Y%m%dT%H%M%S')
      - aws s3 sync ./cypress/videos s3://codebuild-cypress-demo-test-results/$S3_DIR_DATE
      - aws s3 sync ./cypress/screenshots s3://codebuild-cypress-demo-test-results/$S3_DIR_DATE
  post_build:
    commands:
      - echo Test completed on `date`