version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - export SKIP="false"
      - if [[ "$(git log -1 HEAD --pretty=format:%s)" == *\[test\]* ]]; then echo "Installing yarn..." && npm install -g yarn; else export SKIP="true"; fi
  pre_build:
    commands:
      - if [[ "$SKIP" == "true" ]]; then echo "Skipping source NPM dependencies install..."; else echo "Installing source NPM dependencies..." && yarn; fi
  build:
    commands:
      - if [[ "$SKIP" == "true" ]]; then echo "Skipping tests..." && exit 1; else echo "Testing UI..." && yarn test; fi
  post_build:
    commands:
      - echo Test completed on `date`